### ISSUE TITLE
what run

### ISSUE THREAD

**Issue by layerto** [slowwdev/Discord-Selfbot-RPC#2]
run= Index.js or Not?

**Comment by slowwdev** [comment]
> 

yes

**Comment by slowwdev** [comment]
> run= Index.js or Not?

just create a .replit  with run="node index.js"

**Comment by slowwdev** [comment]
ok i created https://github.com/slowwdev/Discord-Selfbot-RPC/commit/f5410781ce0dd387302a8342cba6225a92f96bbb#diff-dabe747bc6b60b9f68c11dfbf2fbc44d3d37bd289e8f7fdc88647cd697d5cbae
