### ISSUE TITLE
Something wrong with game.js

### ISSUE THREAD

**Issue by TileDev** [slowwdev/Discord-Selfbot-RPC#5]
![Screenshot_20211218-235248_Chrome](https://user-images.githubusercontent.com/79881161/146667793-e12e69bc-8032-4973-80e9-6bf7efd0cfb4.jpg)

**Comment by slowwdev** [comment]
> 

ok i fixed (the problem= config.json had applicationID and the game.js has applicationid)
retry :)

**Comment by Random-1s** [comment]
Ah ok ty

**Comment by Random-1s** [comment]
There's another problem, it says that the module express cannot be found

**Comment by Random-1s** [comment]
![Screenshot_20211219-092011_Chrome](https://user-images.githubusercontent.com/79881161/146684368-c423a21d-1e6f-4021-b5a7-a4892bec277d.jpg)

**Comment by slowwdev** [comment]
yes ik the problem i will solve it just wait 👍

**Comment by Random-1s** [comment]
👍

**Comment by slowwdev** [comment]
Problems fixed now, but I will add more features later. Bye
