### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AKPR2007** [slowwdev/Discord-Selfbot-RPC#7]
what do I put in `mode` & `status` in `config.js`

I assume I need to put
**_game/twitch/spotify_**
&&
**_online/dnd/idle_**
But put which in which one ?
Plz reply

Ping (lol) @slowwdev

**Comment by slowwdev** [comment]
> what do I put in `mode` & `status` in `config.js`
> 
> I assume I need to put **_game/twitch/spotify_** && **_online/dnd/idle_** But put which in which one ? Plz reply
> 
> Ping (lol) @slowwdev

Mode: the mode you want (for listening its spotify, for playing its game and for streaming its twitch)

Status: online: Green icon
Dnd: red icon
Idle: 🌙

**Comment by AKPR2007** [comment]
> > what do I put in `mode` & `status` in `config.js`
> > I assume I need to put **_game/twitch/spotify_** && **_online/dnd/idle_** But put which in which one ? Plz reply
> > Ping (lol) @slowwdev
> 
> Mode: the mode you want (for listening its spotify, for playing its game and for streaming its twitch)
> 
> Status: online: Green icon Dnd: red icon Idle: 🌙

@slowwdev can you add timer thing in playing mode. Please it's like one line of code.

**Comment by slowwdev** [comment]
> > > what do I put in `mode` & `status` in `config.js`
> > > I assume I need to put **_game/twitch/spotify_** && **_online/dnd/idle_** But put which in which one ? Plz reply
> > > Ping (lol) @slowwdev
> > 
> > 
> > Mode: the mode you want (for listening its spotify, for playing its game and for streaming its twitch)
> > Status: online: Green icon Dnd: red icon Idle: 🌙
> 
> @slowwdev can you add timer thing in playing mode. Please it's like one line of code.
> 
> I tried this but it didn't work
> 
> 1. `.setStartTimestamp(config.time || Date.now())`
> 2. `.setStartTimestamp(Date.now())`

im not at home but yes i will add later

**Comment by AKPR2007** [comment]
> > > > what do I put in `mode` & `status` in `config.js`
> > > > I assume I need to put **_game/twitch/spotify_** && **_online/dnd/idle_** But put which in which one ? Plz reply
> > > > Ping (lol) @slowwdev
> > > 
> > > 
> > > Mode: the mode you want (for listening its spotify, for playing its game and for streaming its twitch)
> > > Status: online: Green icon Dnd: red icon Idle: 🌙
> > 
> > 
> > @slowwdev can you add timer thing in playing mode. Please it's like one line of code.
> > I tried this but it didn't work
> > 
> > 1. `.setStartTimestamp(config.time || Date.now())`
> > 2. `.setStartTimestamp(Date.now())`
> 
> im not at home but yes i will add later

Sure !!!

**Comment by slowwdev** [comment]
> > > > > what do I put in `mode` & `status` in `config.js`
> > > > > I assume I need to put **_game/twitch/spotify_** && **_online/dnd/idle_** But put which in which one ? Plz reply
> > > > > Ping (lol) @slowwdev
> > > > 
> > > > 
> > > > Mode: the mode you want (for listening its spotify, for playing its game and for streaming its twitch)
> > > > Status: online: Green icon Dnd: red icon Idle: 🌙
> > > 
> > > 
> > > @slowwdev can you add timer thing in playing mode. Please it's like one line of code.
> > > I tried this but it didn't work
> > > 
> > > 1. `.setStartTimestamp(config.time || Date.now())`
> > > 2. `.setStartTimestamp(Date.now())`
> > 
> > 
> > im not at home but yes i will add later
> 
> Sure !!!

done i think in commit 95f8bf59b8971ef7295280cccc9df476bc566de1

**Comment by AKPR2007** [comment]
> > > > > > what do I put in `mode` & `status` in `config.js`
> > > > > > I assume I need to put **_game/twitch/spotify_** && **_online/dnd/idle_** But put which in which one ? Plz reply
> > > > > > Ping (lol) @slowwdev
> > > > > 
> > > > > 
> > > > > Mode: the mode you want (for listening its spotify, for playing its game and for streaming its twitch)
> > > > > Status: online: Green icon Dnd: red icon Idle: 🌙
> > > > 
> > > > 
> > > > @slowwdev can you add timer thing in playing mode. Please it's like one line of code.
> > > > I tried this but it didn't work
> > > > 
> > > > 1. `.setStartTimestamp(config.time || Date.now())`
> > > > 2. `.setStartTimestamp(Date.now())`
> > > 
> > > 
> > > im not at home but yes i will add later
> > 
> > 
> > Sure !!!
> 
> done i think in commit [95f8bf5](https://github.com/slowwdev/Discord-Selfbot-RPC/commit/95f8bf59b8971ef7295280cccc9df476bc566de1)
> 
> remember to use a number WITHOUT STRINGS and an Epoch value https://www.epochconverter.com

Thank you very much. Appreciated
